app:
  log_level: "info"

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0

openai:
  api_key: ""
  model: "gpt-5"
  base_url: "" # optional, e.g., https://api.openai.com/v1

quaily:
  base_url: "https://api.quaily.com/v1"
  api_key: "" # required to publish/send

cloudflare:
  # Cloudflare account ID used to build the fixed scrape endpoint URL.
  # Docs: https://developers.cloudflare.com/browser-rendering/rest-api/
  account_id: ""
  api_token: "" # Cloudflare API token with Browser Rendering permissions

sources:
  v2ex:
    token: "" # Optional V2EX token
    base_url: "https://www.v2ex.com"
    fetch_interval: "10m"
  hackernews:
    base_api: "https://hacker-news.firebaseio.com/v0"
    fetch_interval: "10m"

newsletters:
  output_dir: "./out"
  channels:
    - name: "v2ex_daily_digest"
      source: "v2ex"
      nodes: ["crypto", "solana", "create"]
      frequency: "daily"
      top_n: 20
      min_items: 5
      item_skip_duration: "72h"
      language: "English"
      template:
        title: "V2EX Daily {.CurrentDate}"
        preface: "Your daily V2EX highlights."
        postscript: "Brought to you by Quaily Journalist."
# Notes:
# - The generate command accepts an optional URL list via: `-i urls.txt`.
#   Each line should be a URL. When provided, items are fetched via Cloudflare
#   Browser Rendering API, kept in input order, and rendered without scores.
